spring:
  cloud:
    bus:
      trace:
        enabled: true
#  rabbitmq:
#    host: ${RABBIT_MQ_HOST:localhost}
#    port: ${RABBIT_MQ_PORT:5672}
#    username: ${RABBIT_MQ_USERNAME:guest}
#    password: ${RABBIT_MQ_PASSWORD:guest}
#  redis:
#    host: ${REDIS_HOST:180.76.59.81}
#    port: ${REDIS_PORT:6379}
#    lettuce:
#      pool:
#        max-active: 300
#    ##password: ${REDIS_PASSWORD:}
#    database: 13
#    password: Cheng_Yi_Shu_Yuan_2020.9_DM
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:${DATASOURCE_DBTYPE:mysql}://${DATASOURCE_HOST:175.24.189.176}:${DATASOURCE_PORT:3106}/quarza?characterEncoding=UTF-8&useUnicode=true&useSSL=false&serverTimezone=GMT%2b8
    username: ${DATASOURCE_USERNAME:root}
    password: ${DATASOURCE_PASSWORD:linmaoMysql#222&1}
#  zipkin:
#    enabled: true
#    sender:
#      type: rabbit
#    base-url: http://http://150.158.213.159/:9411
#  sleuth:
#    sampler:
#      probability: 1.0
#    enabled: true
  mvc:
    throw-exception-if-no-handler-found: true
  servlet:
    multipart:
      max-request-size: "2MB"
      max-file-size: "2MB"
  jackson:
    time-zone: GMT+8

  quartz:
    #相关属性配置
    properties:
      org:
        quartz:
          scheduler:
            instanceName: clusteredScheduler
            instanceId: AUTO
          jobStore:
            class: org.quartz.impl.jdbcjobstore.JobStoreTX
            driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
            dataSource: quartzDataSource
            tablePrefix: qrtz_
            isClustered: false #往下是集群的配置
#            clusterCheckinInterval: 10000
#            useProperties: false
#          threadPool:
#            class: org.quartz.simpl.SimpleThreadPool
#            threadCount: 10
#            threadPriority: 5
#            threadsInheritContextClassLoaderOfInitializingThread: true
    #数据库方式
    job-store-type: jdbc
      #初始化表结构
    #jdbc:
    #initialize-schema: never

logging:
  level:
    com.springboot.cloud: debug
    java.sql.PreparedStatement: debug


mybatis-plus:
  type-aliases-package: com.springboot.cloud.quartz.entity
  mapper-locations: classpath:/mapper/*
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      logic-delete-value: "Y" # 逻辑已删除值(默认为 Y)
      logic-not-delete-value: "N" # 逻辑未删除值(默认为 N)
